services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - my-network

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./src:/var/www/src
      - ./vendor:/var/www/vendor
      - ./tests:/var/www/tests
      - ./php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - my-network

  # mysql:
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #     MYSQL_DATABASE: mydatabase
  #     MYSQL_USER: myuser
  #     MYSQL_PASSWORD: mypassword
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  #   networks:
  #     - my-network

# volumes:
#   mysql-data:

networks:
  my-network:
